* Open Issues
** TODO String width calculation is slow on Debian 9
   After implementing pixel-accurate string widths, enabling the mode
   slows down Emacs 25.1 on Debian 9 (and probably other X11
   environments), to the point where splitting a window or having the
   M-x prompt appear takes 1-2 seconds. The cause isn’t clear yet.

   - Do X frames fire many more resize events than Cocoa frames?
   - Is font rendering, or the specific font set, so much slower?
     In both cases Emacs is configured to use Fantasque + Symbola,
     but other fallbacks may be different.
   - Does the overhead of the temporary buffer somehow trigger a bad
     redisplay path specific to X11?

** TODO Scrolling small amounts gets “stuck” on ^Ls.
   Scrolling with the mouse wheel with only three lines per event gets
   stuck, especially near the bottom of the file. This seems to be
   because the scrolling jumps up three visual lines, but only one
   logical line, then back down one logical line during recentering
   during redisplay.

   This may drive me to use overlays rather than display tables, in
   which case the extra space would be handled via a ~line-height~
   property rather than newlines, since text replacement overlays get
   all wonky in a different way when spanning multiple lines.
